### ISSUE TITLE
Configure

### ISSUE THREAD

**Issue by hsnmck** [PurpleI2P/OpenSSL-for-Android-Prebuilt#2]
Hi, is it possible to provide the parameters you used with Configure.sh in order to build openssl. I need to to cross build it for other platforms (arm64 and x86_64).

Thanks

**Comment by r4sas** [comment]
Please read here: https://wiki.openssl.org/index.php/Android#OpenSSL_Library

**Comment by r4sas** [comment]
OpenSSL 1.1.1 published with built for arm64 and x86_64 libraries.
https://github.com/PurpleI2P/OpenSSL-for-Android-Prebuilt/commit/e2e005e2760ceab54cfbf7938ddf2d3f4ea315ac
