### ISSUE TITLE
Do these actually work, since I think versioned .sos are not loaded by Android?

### ISSUE THREAD

**Issue by mavavilj** [PurpleI2P/OpenSSL-for-Android-Prebuilt#5]
Do these actually work, since I think versioned .sos are not loaded by Android?

Such as suggested in: https://stackoverflow.com/questions/24204366/how-to-build-openssl-as-unversioned-shared-lib-for-android/33869277#33869277

**Comment by r4sas** [comment]
They works, I have used them for i2pd android app for 4 years, until we switched to build flavor for CI.

**Comment by mavavilj** [comment]
In that case,

Could you tell me how to get around the "cannot find xxxxxx.so.1.1" problem similar to:

https://stackoverflow.com/questions/48929228/external-library-and-jni-with-android-dlopen-failed-library-libcrypto-so-1-1

When I tried to include these, then only the unversioned .sos get into the final APK.

**Comment by mavavilj** [comment]
Even better if someone can provide a pre-made CMakeLists.txt or a full Android Studio project.

**Comment by mavavilj** [comment]
I think the i2pd source might be out-dated, because it also relies on .sh scripts whose execution is non-trivial or impossible due to the new Android security measures. 

But I also saw the i2pd only seems to link to the unversioned .a files. Does it actually use the versioned ones at all?

**Comment by mavavilj** [comment]
Or well, you could've maybe clarified if you meant that you're meant to use the static libraries for Android, not the dynamic .sos.

**Comment by mavavilj** [comment]
Yes, so they do work, but one has to use the unversioned, static .a libraries on Android.

**Comment by r4sas** [comment]
We used unversioned links to .a libraries with version in name, like in Linux systems it works.
